<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="6" failures="0" skipped="0" tests="6" time="0.374" timestamp="2023-04-27T01:14:17.385368" hostname="DESKTOP-EJ8E5Q7"><testcase classname="" name="pig_game.test_dice" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\gifty\Documents\FinalVersionSustainable\pig_game\test_dice.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pig_game\test_dice.py:4: in &lt;module&gt;
    from dice import Dice
E   ModuleNotFoundError: No module named 'dice'</error></testcase><testcase classname="" name="pig_game.test_game" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\gifty\Documents\FinalVersionSustainable\pig_game\test_game.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pig_game\test_game.py:2: in &lt;module&gt;
    from game import Game
E   ModuleNotFoundError: No module named 'game'</error></testcase><testcase classname="" name="pig_game.test_highscore" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\gifty\Documents\FinalVersionSustainable\pig_game\test_highscore.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pig_game\test_highscore.py:2: in &lt;module&gt;
    from highscore import Highscore
E   ModuleNotFoundError: No module named 'highscore'</error></testcase><testcase classname="" name="pig_game.test_intelligence" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\gifty\Documents\FinalVersionSustainable\pig_game\test_intelligence.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pig_game\test_intelligence.py:2: in &lt;module&gt;
    from dice import Dice
E   ModuleNotFoundError: No module named 'dice'</error></testcase><testcase classname="" name="pig_game.test_main" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\gifty\Documents\FinalVersionSustainable\pig_game\test_main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pig_game\test_main.py:3: in &lt;module&gt;
    from game import Game, Die, Computer, Player
E   ModuleNotFoundError: No module named 'game'</error></testcase><testcase classname="" name="pig_game.test_player" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\gifty\Documents\FinalVersionSustainable\pig_game\test_player.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pig_game\test_player.py:3: in &lt;module&gt;
    from dice import Dice
E   ModuleNotFoundError: No module named 'dice'</error></testcase></testsuite></testsuites>